# Generated by Django 2.0.4 on 2020-02-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='ブランドコード')),
                ('name', models.CharField(max_length=64, verbose_name='ブランド名')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='品番')),
                ('brand_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='manager.Brand', verbose_name='ブランドコード')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('brand_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='manager.Brand', verbose_name='ブランドコード')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='manager.Product', verbose_name='品番')),
            ],
        ),
    ]
