# Generated by Django 2.0.4 on 2020-02-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_code',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='brand_code',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='product_code',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=64, verbose_name='品番'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(max_length=64, verbose_name='SKU'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='sku',
            unique_together={('brand', 'code')},
        ),
    ]
