# Generated by Django 2.0.4 on 2020-02-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200229_2241'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='sku',
            table='sku',
        ),
    ]
